version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: bugtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bugtracker-net

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://pguser:pwd123@db:5432/bugtracker"
    networks:
      - bugtracker-net

volumes:
  postgres_data:

networks:
  bugtracker-net:
